### ISSUE TITLE
Changes Requested for AppCenter: Don't use other apps' private API

### ISSUE THREAD

**Issue by cassidyjames** [Timecraft/JS_Test#64]
This seems really clever, but relying on other apps' private API (i.e. their GSettings) is unreliable and error-prone. We have amended the [Technical Publishing Requirements](https://github.com/elementary/houston/wiki/Before-You-Publish#technical-requirements) to include:

>Your app must not attempt to modify other apps or system programs. **Your app should not rely on other apps' GSettings, as these are considered internal/private API for those apps.**

https://github.com/Timecraft/JS_Test/blob/eb4d66955b4d63b37134c86305b2a1a1be1da5b6/src/Views/SourceView.vala#L67-L94

**Comment by Timecraft** [comment]
Understood. Marking this with #8, and modifying it to reflect this. I will completely restructure JS Test's GSettings to be self-contained. Thanks much, sir!
