### ISSUE TITLE
<body> element does not exist

### ISSUE THREAD

**Issue by RubenSibon** [Timecraft/JS_Test#69]
No matter what method I try, I can't select the body element. It always returns `null`.

**Does not work:**

`var body = document.body;`
`var body = document.querySelector("body");`
`var body = document.getElementsByTagName("body")[0];`

Interestingly I can select the `<html>` and `<head>` elements.

What does work is to use the console variable `$0` in the developer tools to select the body. But from the <s>sidebar</s> codepanel I can't reach it.

I tried restarting the app.

**Comment by Timecraft** [comment]
I'll have to look and see if the WebView has anything it generates as well, but in (WebView.vala)[https://github.com/Timecraft/js-test/blob/master/src/Views/WebView.vala], there is no `<body>` element while there are both`<head>` and `<html>` elements. So, unless the WebView is generating elements and I'm not currently aware of it, that should be expected. 
Regardless of whether this is what should be happening or not, it is not optimal and a developer would expect there to be a `<body>` element to select, so I will add it in there. Thank you for the report!

**Comment by RubenSibon** [comment]
Might be that in Vala's WebView there is no `<body>`, but in the inspector it is there together with `<html>`, `<head>` and a `<script>` tag.

**Comment by Timecraft** [comment]
With the latest [commit](https://github.com/Timecraft/js-test/commit/19cc22b5b513d1e25c7523909477eff0e59b8b32), this issue should be fixed. I tried just adding the element, but it still showed as null. I had to move the `<script>` element out of the `<head>` and added the `<body>` element before any scripts are run. Could you verify that this works now?

**Comment by RubenSibon** [comment]
Yup, it's solved. Deferring the script was the solution.

![Schermafdruk van 2020-02-18 20-01-50](https://user-images.githubusercontent.com/7290629/74768888-b215ed00-5289-11ea-9c13-42d29768ce9a.png)

**Comment by Timecraft** [comment]
Let’s not close this just yet. I want to close this when I commit it to the stable branch (Hera)
